apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUkrcmU5Zi81SFNxdWVWeHRYVnhWSGN3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEE1TWpZeU1qRTRNek5hRncwek5UQTVNalF5TWpFNApNek5hTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVNHdGJreVNOTWtVWTgxelBzV1FvQUN1NXFsbmEyR0FjeGp3NTM2Yis1TXNRa3piczkrYlc2MWNqSlQKUzNTQ3k4NTVVa2YrZ05IYzdXWklFYjhvaE5leW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTUNIT0MzRThuQTd5akRLMDBjaE5kM3hxamN5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUJadS8zdjQKTUdvS05GMnRac1RHZms1RlloajlVTm5FcThYZUpWRExPUTkxQWlFQWdRS0tORWZhUnh1N29zcTJ2Yzk5ZmRSbQpkaUhoSThhMzRUREJFeW5qVWUwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.122.217:6443
  name: cozystack
contexts:
- context:
    cluster: cozystack
    namespace: default
    user: admin@cozystack
  name: admin@cozystack
current-context: admin@cozystack
kind: Config
preferences: {}
users:
- name: admin@cozystack
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoRENDQVNxZ0F3SUJBZ0lRQ2szQ1RVdUl3ZHV1MU14M2RCL0czekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRGt5TmpJeU5UTTFOMW9YRFRJMk1Ea3lOakl5TlRRdwpOMW93S1RFWE1CVUdBMVVFQ2hNT2MzbHpkR1Z0T20xaGMzUmxjbk14RGpBTUJnTlZCQU1UQldGa2JXbHVNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFU3U2U29YcnExb1VoUm44N3h0T1Q2OUlJSk1MWU44NzkKMDVIQWFIdGYyV0hXRkpFQjVnS3RxbnVLS0hwQlM3eDFpQkRaTjZ2dkdpVWtsdGJKMFAzTDdhTklNRVl3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01COEdBMVVkSXdRWU1CYUFGTUNICk9DM0U4bkE3eWpESzAwY2hOZDN4cWpjeU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ2VRT0p2MnR0RTArS2QKT1dIRnNUSHhMMks3NXpFK1Zma3I3ajRKS3k3NlJRSWdabkttckk4RjFCUzRPUWN0a01iUlZGK1BxdkxiWEVobApoc3dza1ZpdmRXND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZwMSt2MWJTTitSZ0RTOS9la3VzOCt3U044b0lsNWgraURHVzBkQkZxNTdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFU3U2U29YcnExb1VoUm44N3h0T1Q2OUlJSk1MWU44NzkwNUhBYUh0ZjJXSFdGSkVCNWdLdApxbnVLS0hwQlM3eDFpQkRaTjZ2dkdpVWtsdGJKMFAzTDdRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
